/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 08 05:09:43 GMT 2020
 */

package esc.problemset3.question7;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import esc.problemset3.cohortexercise07.Example3;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example3_ESTest extends Example3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(2.0, 2.0, 1739);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(2934, 81.00681389555213, 2934);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(2550, 1.0, 2550);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(0.6627357917231369, 0.6627357917231369, 1739);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(683.88315531245, 683.88315531245, 0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(2.0, 0.0, (-1));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(0.0, (-2124), (-1448));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(1351.0, 1351.0, 1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(2542, 0.09825902804916997, 2542);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(1.0, 1.0, 3);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(1935.42847, 2542, (-1));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(2561.12899, (-1668.99237205), (-1448));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test(1.9389990886976889, 1.9389990886976889, 1739);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Example3 example3_0 = new Example3();
      example3_0.test((-574.5484003818303), (-574.5484003818303), (-2124));
  }
}
