/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 08 07:45:37 GMT 2020
 */

package esc.problemset3.question7;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import esc.problemset3.cohortexercise07.Example;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Example example0 = new Example();
      example0.test(7.032493944005674, 13.107650487465, 0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Example example0 = new Example();
      example0.test(13.107650487465, 13.111239409906892, 3);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Example example0 = new Example();
      example0.test(5.0, 13.107650487465, 2143953870);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 16.0, 1816);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-3183.943012401878), 10.0, 0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Example example0 = new Example();
      example0.test(528.0, (-2490.894361927405), 1840700269);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Example example0 = new Example();
      example0.test(5.3516883545, 10.486080151828366, (-2135977608));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Example example0 = new Example();
      example0.test(13.107650487465, 13.111239409906892, 1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Example example0 = new Example();
      example0.test(7, 13.1112394, 7);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Example example0 = new Example();
      example0.test(7, 438.95662, 7);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Example example0 = new Example();
      example0.test(2.120496322993386, 5.0, (-2135977608));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Example example0 = new Example();
      example0.test(1, 13.111239409906892, 1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Example example0 = new Example();
      example0.test(13.111239409906892, 13.111239409906892, 1);
  }
}
